// Civic Editorial nearby view: a map-led composition pairs location context with lightweight community signals and an explicit privacy reminder.
import { useState } from "react";
import { Check, ChevronRight, LocateFixed, MapPin, Navigation, Radio, Search, ThumbsUp } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";
import CivicShell from "@/components/CivicShell";
import { MapView } from "@/components/Map";
import { mockIssues } from "@/data/mockData";

export default function Nearby() {
  const [selected, setSelected] = useState(mockIssues[0].id);
  const [supported, setSupported] = useState<string[]>([]);
  const selectedIssue = mockIssues.find((issue) => issue.id === selected) ?? mockIssues[0];
  const toggleSupport = (id: string) => setSupported((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]);

  return <CivicShell title="What’s happening nearby" eyebrow="Neighborhood view" action={<div style={{ display: 'flex', gap: '10px' }}><Link href="/intelligence" className="button" style={{ background: '#163438', color: '#75C7B2', border: '1px solid #75C7B2' }}><Radio size={16} className="spin-slow" /> GIS Command View</Link><Link href="/report" className="button button-primary"><span>+</span> Report an issue</Link></div>}>
    <div className="nearby-layout"><div className="map-column"><div className="map-topline"><div><span className="section-kicker">Within 1.5 miles</span><h2>District 4 issue map</h2></div><div style={{ display: 'flex', gap: '8px' }}><button className="location-chip" onClick={() => toast.success("Map centered on your district.")}><LocateFixed size={15} /> My area</button><Link href="/intelligence" className="location-chip" style={{ textDecoration: 'none', background: '#e0f2fe', color: '#0369a1', borderColor: '#38bdf8' }}><Radio size={13} /> Full GIS Heatmap</Link></div></div><div className="nearby-map"><MapView initialCenter={{ lat: 40.7411, lng: -73.9897 }} initialZoom={14} onMapReady={(map) => { if (!window.google?.maps?.marker) return; mockIssues.forEach((issue) => new window.google.maps.marker.AdvancedMarkerElement({ map, position: issue.coordinates, title: issue.title })); }} /><div className="map-radius-label"><span className="radius-dot" /> 3 active reports in your area</div><div className="map-fallback-pattern" aria-hidden="true"><span className="road road-a" /><span className="road road-b" /><span className="road road-c" /><span className="map-pin pin-a"><i>1</i></span><span className="map-pin pin-b"><i>2</i></span><span className="map-pin pin-c"><i>3</i></span></div></div><div className="map-legend"><span><i className="legend-dot mint" /> In progress</span><span><i className="legend-dot coral" /> Needs review</span><span><i className="legend-dot ink" /> Resolved</span><span className="map-privacy"><Navigation size={13} /> Approximate locations shown · <Link href="/intelligence" style={{ color: 'var(--moss-deep)', fontWeight: 600 }}>Open Command Center</Link></span></div></div>
      <aside className="nearby-list"><div className="nearby-search"><Search size={16} /><input placeholder="Search this area" aria-label="Search this area" /></div><div className="nearby-list-head"><span>{mockIssues.length} visible reports</span><button>Latest <ChevronRight size={14} /></button></div><div className="nearby-cards">{mockIssues.map((issue) => { const isSelected = issue.id === selected; const isSupported = supported.includes(issue.id); return <button key={issue.id} className={`nearby-card ${isSelected ? "selected" : ""}`} onClick={() => setSelected(issue.id)}><div className="nearby-card-image"><img src={issue.image} alt="" /><span className={`nearby-status ${issue.status === "Resolved" ? "resolved" : issue.status === "In progress" ? "progress" : "review"}`} /></div><div className="nearby-card-copy"><div className="nearby-card-meta"><span>{issue.id}</span><span>{issue.updatedAt}</span></div><h3>{issue.title}</h3><p><MapPin size={12} /> {issue.location}</p><div className="nearby-card-footer"><span className="nearby-card-status">{issue.status}</span><span className="nearby-support"><ThumbsUp size={13} /> {issue.supporters + (isSupported ? 1 : 0)}</span></div></div><ChevronRight size={16} className="nearby-arrow" /></button>; })}</div><div className="selected-support"><div><span className="section-kicker">Selected report</span><h3>{selectedIssue.title}</h3><p>{selectedIssue.supporters + (supported.includes(selectedIssue.id) ? 1 : 0)} neighbors are paying attention.</p></div><button className={`support-mini ${supported.includes(selectedIssue.id) ? "supported" : ""}`} onClick={() => { toggleSupport(selectedIssue.id); toast.success(supported.includes(selectedIssue.id) ? "Support removed." : "Thanks for supporting this report."); }}>{supported.includes(selectedIssue.id) ? <Check size={15} /> : <ThumbsUp size={15} />}</button></div><Link href={`/issues/${selectedIssue.id}`} className="text-link nearby-detail-link">Open full report <ChevronRight size={14} /></Link></aside>
    </div>
  </CivicShell>;
}
